#pragma once

#include "EngineIsOffException.h"
#include "FailedToAccelerateException.h"
#include "FailedToEngineOffWhileMovingException.h"
#include "FailedToReverseWhileMovingException.h"
#include "FailedToSetSpeedWhileEngineOffException.h"
#include "GearIsOutOfRangeException.h"
#include "InvalidCommandArgumentException.h"
#include "NegativeSpeedException.h"
#include "SpeedIsOutOfRangeException.h"
#include "UnknownCommandException.h"
#include "WrongCurrentSpeedException.h"
#include "WrongInputException.h"
#include "FailedToIncreaseGearException.h"
